name: PR Checks

on:
  pull_request:
    branches:
      - main

jobs:
  install-dependencies:
    permissions:
      contents: read
      pull-requests: read
      packages: read
    uses: ./.github/workflows/install-dependencies.yml

  unit-tests:
    needs:
      - install-dependencies
    permissions:
      contents: write
      pull-requests: read
      actions: read
    uses: ./.github/workflows/unit-tests.yml

  lint:
    needs:
      - install-dependencies
    permissions:
      contents: read
      pull-requests: read
    uses: ./.github/workflows/lint.yml
